apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager-sample
  namespace: 3scale
spec:
  system:
    fileStorage:
      persistentVolumeClaim:
        storageClassName: managed-nfs-storage
  wildcardDomain: dev.t.st
