kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name:  3scale
  annotations:
    openshift.io/node-selector: "node-role.kubernetes.io/rhintegration=" 
    scheduler.alpha.kubernetes.io/defaultTolerations: >-
      [{"operator": "Exists", "effect": "NoSchedule", "key":
      "node-role.kubernetes.io/rhintegration"} 
      ]
